"use client"

import Layout from  "@/app/components/Layout"
import BlogPost from '@/app/components/BlogPost'
import CommentBox from  '@/app/components/CommentBox'
type params = Promise<{id :string}>


const blogPosts = [
  { id: 1, title: "The Future of AI",
    content: "Artificial Intelligence (AI) is rapidly evolving and its impact on various industries is becoming increasingly significant. From healthcare to finance, AI is revolutionizing the way we work and live.\n\nOne of the most exciting areas of AI development is machine learning, which allows systems to improve their performance without being explicitly programmed. This has led to breakthroughs in areas such as natural language processing, computer vision, and predictive analytics.\n\nAs AI continues to advance, we can expect to see more personalized and efficient services in our daily lives. However, this rapid progress also raises important ethical questions about privacy, job displacement, and the role of AI in decision-making processes.\n\nIt is crucial for society to engage in ongoing discussions about the responsible development and deployment of AI technologies. By doing so, we can harness the potential of AI while mitigating its risks, ensuring a future where technology enhances human capabilities rather than replacing them",
    imageUrl: "/a1.jpeg" },

    { id: 2, title: "5G Technology",
      content: "5G technology represents the next generation of wireless connectivity, promising faster speeds, lower latency, and greater capacity for connected devices. With the rollout of 5G networks globally, industries are on the brink of transformative changes, from enhanced mobile experiences to advanced IoT deployments.\n\nUnlike previous generations of wireless technology, 5G is designed to handle massive amounts of data transfer efficiently, supporting applications such as autonomous vehicles, smart cities, and real-time communication in industries like healthcare and logistics. The speed and reliability of 5G networks enable real-time data processing and seamless connectivity for devices, which is essential for modern, data-driven ecosystems. Furthermore, 5G enhances the ability to support connected devices in densely populated areas, such as urban environments, where traditional networks may face congestion.\n\nThe impact of 5G extends far beyond mobile phones and internet browsing, with implications for industries such as manufacturing, agriculture, and entertainment. In manufacturing, 5G-powered IoT solutions allow for real-time monitoring and predictive maintenance, improving efficiency and reducing downtime. Similarly, in healthcare, 5G enables remote surgery and telemedicine with minimal latency, ensuring optimal care for patients. However, with the benefits come challenges such as infrastructure investment, cybersecurity risks, and the need for a robust regulatory framework.\n\nEnsuring widespread 5G deployment while maintaining security will be critical as businesses and governments explore the full potential of this transformative technology",     imageUrl: "/b.jpeg" },

     { id: 3, title: "Crisis in Pakistan",
      content: "The political and economic landscape in Pakistan has been grappling with multiple crises, posing significant challenges for its citizens and the government.\n\nOne of the most pressing issues is the economic instability faced by the country. High inflation, a depreciating currency, and a widening gap between income and expenditure have led to a difficult environment for the average Pakistani. Businesses are struggling with rising costs, while unemployment continues to rise, exacerbating social unrest.\n\nOn the political front, governance has faced criticism for its inability to address these challenges effectively. Corruption, lack of transparency, and poor policy implementation have hindered progress in various sectors, leading to a trust deficit between the government and its people.\n\nAdditionally, security concerns remain a major crisis in Pakistan. Ongoing conflict in certain regions, terrorism, and extremism continue to pose threats to peace and stability. The governments efforts to counter these issues are met with limited success, impacting the overall quality of life and development.\n\nIn response to these crises, civil society, political activists, and international organizations are urging for sustainable solutions, focusing on good governance, economic reforms, and conflict resolution to pave the way for a more stable and prosperous future for Pakistan",
           imageUrl: "/c2.webp" },

     { id: 4, title: "Syrian Collapse",
      content:" The fall of Syria s government has been a complex and prolonged crisis, marked by years of conflict, political instability, and humanitarian suffering.\n\nThe Syrian Civil War, which began in 2011, was fueled by widespread discontent with the authoritarian rule of President Bashar al-Assad and his regime. Protests calling for democratic reforms quickly escalated into a full-scale conflict as the government responded with violence, repression, and the use of military force against civilians.\n\nOver the years, the conflict has evolved into a multifaceted war involving various factions, including opposition groups, jihadist organizations, Kurdish militias, and international powers like Russia and the United States. The ongoing power struggle has devastated the countrys infrastructure, displacing millions of people, and creating one of the worst humanitarian crises in modern history.\n\nDespite multiple peace efforts and international negotiations, including the involvement of the United Nations and other global actors, a comprehensive resolution remains elusive. The Assad governments hold on power has been maintained through military intervention and foreign support, yet internal divisions and economic hardships continue to weaken the state.\n\nThe fall of Syria s government would require a sustained, coordinated effort to address the deep-seated issues of governance, justice, and reconciliation, offering hope for a peaceful and democratic future for its citizens",
           imageUrl: "/d2.webp" },

     { id: 5, title: "The Palestinian Issue",
content: "The Palestinian issue is deeply rooted in history, dating back to the early 20th century when competing national movements and colonial powers shaped the future of the region. The establishment of Israel in 1948 and the subsequent displacement of hundreds of thousands of Palestinians, known as the Nakba (catastrophe), marked a turning point that continues to shape the narrative. Today, Palestinians in the occupied territories of the West Bank, East Jerusalem, and Gaza Strip face daily challenges, including restricted mobility, loss of property, and limited access to essential services.\n\nOne of the most alarming aspects of the conflict is the humanitarian crisis in Gaza. Often described as the worlds largest open-air prison, Gaza faces severe economic and social challenges due to blockades and recurring conflicts. Basic necessities like clean water, electricity, and medical supplies are scarce, leaving millions to live under dire conditions. International organizations have repeatedly called for action, yet the situation remains largely unresolved, leaving the people of Gaza to endure a cycle of poverty and violence.\n\nThe international response to the Palestinian issue has been inconsistent, with some countries calling for immediate action and others supporting the status quo. Numerous United Nations resolutions have called for the recognition of Palestinian rights, yet their implementation has been minimal. The lack of accountability for violations of international law further exacerbates the conflict, undermining efforts for peace and justice. This has fueled frustration among Palestinians, who continue to seek recognition and freedom through peaceful and diplomatic means as well as resistance.\n\nThe Palestinian issue is not just a regional conflict; it is a matter of global conscience and human rights. For decades, the struggle of the Palestinian people has symbolized the universal fight for justice, equality, and self-determination. Despite the hardships and setbacks, their resilience and hope remain unwavering. The international community has a moral obligation to prioritize dialogue, enforce accountability, and support peaceful resolutions that address the legitimate aspirations of both Palestinians and Israelis. A just and lasting solution can only be achieved through mutual understanding, the protection of human rights, and the recognition of the Palestinian people s right to live with dignity and freedom. By fostering compassion and collaboration, the world can move closer to ensuring a peaceful and equitable future for all in the region",
     imageUrl: "/e1.png" },



     { id: 7, title: "Parachinar Conflict",
      content: " Parachinar, the capital of Kurram District in Pakistan s Khyber Pakhtunkhwa province, has recently experienced significant unrest. On November 21, 2024, a tragic incident occurred when gunmen ambushed a convoy of over 200 vehicles transporting Shia Muslims from Parachinar to Peshawar. The attackers initially targeted police escort vehicles before opening fire on passengers, resulting in at least 54 deaths and 86 injuries. This event marked one of the deadliest sectarian attacks in the region in recent years \n\nThe aftermath of the attack led to widespread sectarian clashes throughout Kurram District. Rioters in villages such as Bagan and Bacha Kot set fire to shops, houses, and government buildings. In Parachinar, protesters torched two police checkpoints. The violence caused internet shutdowns, suspension of mobile services, school closures, and severe shortages of essential goods like food and medicine. By December 3, 2024, the death toll from these clashes had risen to 133, with 177 individuals wounded \n\nn response to the recent violence in Parachinar, Karachi has witnessed widespread protests and sit-ins organized by various groups, including the Majlis Wahdat-e-Muslimeen (MWM) and the Ahle Sunnat Wal Jamaat (ASWJ). These demonstrations have been held at multiple locations across the city, with participants expressing solidarity with the victims and demanding justice. The protests have led to significant traffic disruptions, with roads blocked and public transportation affected. Authorities have implemented measures to manage the situation, including the deployment of law enforcement personnel and the establishment of a 24/7 helpline by Karachi Traffic Police to assist with traffic-related issues \n\nThe protests have drawn attention to the ongoing sectarian violence in Parachinar, highlighting the need for effective conflict resolution and peace-building initiatives. While the demonstrations have been largely peaceful, there have been instances of tension and clashes between protesters and law enforcement agencies. The situation remains fluid, and authorities are urging calm while they work towards restoring peace and addressing the underlying causes of the conflict. \n\nThe situation in Parachinar remains critical, with ongoing unrest and sectarian violence impacting both the local community and surrounding regions. In Karachi, protests have highlighted the deep concerns and frustrations regarding the recent tragic events. While authorities are making efforts to manage the situation, including deploying security forces and implementing measures to maintain order, there is a pressing need for lasting peace-building initiatives. Unity, understanding, and dialogue are essential for addressing the root causes of conflict and restoring stability to Parachinar and other affected areas. Continued vigilance and support from both local and national stakeholders will be crucial in navigating through this challenging period", 
     imageUrl: "/f3.webp" },

     { id: 6, title: "Champion Trophy-2025",
      content: "The ICC Champion Trophy is one of the most prestigious cricket tournaments in the world, and when hosted in Pakistan, it brings together top cricketing nations in a celebration of the sport. For a country like Pakistan, which has a rich cricketing history and a passionate fan base, the preparation for hosting and participating in such events is a huge endeavor. Lets take a look at which teams participate in the Champion Trophy and which cities are ready to host this grand tournament. \n\nPakistan, as the host nation, plays a crucial role in organizing and showcasing the tournament. Several cities across the country are ready to host these high-profile matches, including Lahore, Karachi, Rawalpindi, Multan, Faisalabad, and Sialkot. Lahore, with its iconic Gaddafi Stadium, and Karachi, home to the modern National Stadium, are among the key venues that offer state-of-the-art facilities. \n\nCities like Rawalpindi, Multan, and Faisalabad are also emerging as promising host locations with well-equipped stadiums to support international events. Together, these cities provide a vibrant backdrop for the Champion Trophy, ensuring a memorable experience for both players and fans alike.\n\nThe ICC Champion Trophy in Pakistan is more than just a sporting event; it is a celebration of the countrys rich cricketing heritage and the passion of its people. Hosting such a prestigious tournament showcases Pakistans ability to organize world-class events, with top-tier facilities and a dedicated fan base that creates an electrifying atmosphere at every match. Cities like Lahore, Karachi, Rawalpindi, and Multan have proven their capability to host international cricket, offering state-of-the-art stadiums and ensuring a seamless experience for players and spectators alike. This event not only highlights the talent of the participating teams but also unites the nation in support of cricket. \n\nThe conclusion of the ICC Champion Trophy in Pakistan is always a moment of celebration and reflection. The tournament not only showcases world-class cricket but also highlights the unity and passion that the sport brings to the nation. Pakistan s success in hosting such a prestigious event is a testament to the countrys dedication to cricket, its infrastructure, and the overwhelming support of its cricket-loving population. With each edition, the Champion Trophy leaves a lasting impact, fostering greater camaraderie among nations and strengthening Pakistans position on the global cricketing map.", 
     imageUrl: "/g3.webp" },

     { id: 8, title: "The Rise of Social Media",
      content: "The rise of Social Media has revolutionized the way people interact, share information, and conduct business. Platforms like Facebook, Instagram, Twitter, and TikTok have become essential tools for connecting with friends, family, and even professional networks. Social media has broken geographical boundaries, allowing individuals to communicate instantly across the globe, fostering a sense of community and collaboration. Furthermore, businesses have harnessed the power of social media to reach wider audiences, promote their brands, and engage with customers directly through targeted marketing and content creation. \n\nHowever, with its rapid growth, social media also faces challenges. Issues such as privacy concerns, fake news, and the spread of misinformation have become more prominent, prompting discussions about the ethical use of these platforms. Additionally, the addictive nature of social media has led to concerns about mental health and the impact of constant digital engagement on well-being. Despite these challenges, social media continues to evolve, incorporating new technologies like augmented reality and artificial intelligence to enhance user experiences and create more interactive environments. \n\nIn recent years, social media has also become a powerful tool for social and political movements, empowering individuals to voice their opinions and rally for change. From grassroots activism to global awareness campaigns, platforms have amplified voices and driven real-world impact. As the landscape continues to shift, social media remains a dynamic space that influences culture, business, and communication on a global scale.", 
     imageUrl: "/h1.jpg" },

 
]



// export default function BlogPostPage({ params }: { params: { id: string } }) {
//   const post = blogPosts.find(p => p.id === parseInt(params.id));

//   if (!post) {
//     return <div>Post not found</div>;
//   }

//   return (
//     <Layout>
//       <BlogPost {...post} />
//       <CommentBox />
//     </Layout>
//   );
// }


export default function BlogPostPage({ params }: { params: { id: string } }) {
  const post = blogPosts.find(p => p.id === parseInt(params.id));

  return (
    <Layout>
      {post ? <BlogPost {...post} /> : null}
      <CommentBox />
    </Layout>
  );
}